# Generated by Django 5.2.6 on 2025-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('location_id', models.CharField(max_length=128)),
                ('location_name', models.CharField(blank=True, default='', max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_type', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['location_id'], name='api_feedbac_locatio_4c5100_idx'), models.Index(fields=['region', 'place_type'], name='api_feedbac_region_a0a22e_idx')],
            },
        ),
    ]
