# Generated by Django 5.2.6 on 2025-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_trusted_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rejected_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedback',
            name='validation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['approval_status'], name='api_feedbac_approva_93ee35_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user_id', 'approval_status'], name='api_feedbac_user_id_e6ac2a_idx'),
        ),
    ]
